CREATE TABLE  PLAYERS (
  PLAYER_ID		BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME	 		varchar(50) NOT NULL,
  EMIL 			varchar(100) NOT NULL,
  PHONE_NUMBER 	varchar(15) NOT NULL,
  USER_ID 		varchar(50) NOT NULL,
  PASSWORD		varchar(20) NOT NULL
 
) ;

CREATE TABLE COURSES(
  COURSE_ID	     BIGINT AUTO_INCREMENT PRIMARY KEY,
  COURSE_NAME    varchar(80) NOT NULL,
  SLOPE		     int(4) NOT NULL,
  RATING 		 float(4) NOT NULL,
  YARDAGE 	     int(4) NOT NULL,
  COMMENT 	     varchar(30) NOT NULL
);

CREATE TABLE ROUND(
  ROUND_ID	 	    BIGINT AUTO_INCREMENT PRIMARY KEY,
  PLAYER_ID 		int(11) NOT NULL,
  ROUND_DATE 	    DATETIME NOT NULL,
  NAME   			varchar(50) NOT NULL,
  COURSE 			varchar(50) NOT NULL,
  SCORE 			int(4) NOT NULL,
  SLOPE 			int(4) NOT NULL,
  RATING			float(4) NOT NULL,
  DELTA 			float(4) NOT NULL,
  INUSE             BOOLEAN NOT NULL
  
) ;
